language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_script:
  - chmod -R a+x .
script:
  - ./package.sh --quiet verify
  - ./publish.sh --quiet verify
addons:
  apt:
    packages:
      - docker-ce
